language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  include:
    - php: 5.3
      dist: precise
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

dist: trusty
sudo: false